const cardsTab = [
    //2 costs --------------------------
    {
        id: 1,
        name: "Chevalier",
        hp: 1260,
        damages: 63,
        range: 1,
        speed: "normal",
        atqSpeed: 1.66,
        critical: 0.15,
        type: "cummun",
        img: ".png",
        cout: 2,
        categories: [0,1],
    },
    {
        id: 2,
        name: "Archères",
        hp: 480,
        damages: 84,
        range: 4,
        speed: "normal",
        atqSpeed: 1.00,
        critical: 0.15,
        type: "cummun",
        img: ".png",
        cout: 2,
        categories: [3,2],
          },
    {
        id: 3,
        name: "Goblin",
        hp: 504,
        damages: 108,
        range: 1,
        speed: "normal",
        atqSpeed: 0.66,
        critical: 0.15,
        type: "cummun",
        img: ".png",
        cout: 2,
        categories: [4,5],
    },
    {
        id: 4,
        name: "Gobelin à lance",
        hp: 360,
        damages: 180,
        range: 3,
        speed: "normal",
        atqSpeed: 1.66,
        critical: 0.15,
        type: "cummun",
        img: ".png",
        cout: 2,
        categories: [4,6],
    },
    {
        id: 5,
        name: "Barbares",
        hp: 882,
        damages: 100,
        range: 1,
        speed: "normal",
        atqSpeed: 1.00,
        critical: 0.15,
        type: "cummun",
        img: ".png",
        cout: 2,
        categories: [3,7],
    },
    {
        id: 6,
        name: "Dragons squelettes",
        hp: 345,
        damages: 80,
        range: 4,
        speed: "normal",
        atqSpeed: 1.25,
        critical: 0.15,
        type: "cummun",
        img: ".png",
        cout: 2,
        categories: [8,2],
    },
    {
        id: 7,
        name: "Sorcier",
        hp: 462,
        damages: 92,
        range: 4,
        speed: "normal",
        atqSpeed: 1.25,
        critical: 0.15,
        type: "cummun",
        img: ".png",
        cout: 2,
        categories: [10,9],
    },
    // 3 costs --------------------------
    {
        id: 8,
        name: "Mousquetaire",
        hp: 922,
        damages: 92,
        range: 3,
        speed: "normal",
        atqSpeed: 1.66,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [0,6],
    },      
    {
        id: 9,
        name: "Valkyrie",
        hp: 1269,
        damages: 127,
        range: 1,
        speed: "normal",
        atqSpeed: 1.66,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [3,1],
    },
    {
        id: 10,
        name: "Pekka",
        hp: 1374,
        damages: 378,
        range: 1,
        speed: "Très lent",
        atqSpeed: 2.50,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [12,11],
    },
    {
        id: 11,
        name: "Prince",
        hp: 872,
        damages: 150,
        range: 1,
        speed: "normal",
        atqSpeed: 1.25,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [0,7],
    },
    {
        id: 12,
        name: "Géant squelette",
        hp: 1030,
        damages: 56,
        range: 1,
        speed: "Très lent",
        atqSpeed: 1.66,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [8,7],
    },
    {
        id: 13,
        name: "Gobelin à sarbacane",
        hp: 634,
        damages: 80,
        range: 5,
        speed: "normal",
        atqSpeed: 0.83,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [4,2],
    },
    {
        id: 14,
        name: "Géant électrique",
        hp: 1090,
        damages: 68,
        range: 1,
        speed: "Très lent",
        atqSpeed: 1.42,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [13,11],
    },
    {
        id: 15,
        name: "Bourreau",
        hp: 763,
        damages: 130,
        range: 4,
        speed: "normal",
        atqSpeed: 2.00,
        critical: 0.15,
        type: "rare",
        img: ".png",
        cout: 3,
        categories: [12,6],
    },
    // 4 costs --------------------------
    {
        id: 16,
        name: "Sorcière",
        hp: 709,
        damages: 87,
        range: 4,
        speed: "normal",
        atqSpeed: 2.00,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [8,11],
    },
    {
        id: 17,
        name: "Bébé dragon",
        hp: 780,
        damages: 154,
        range: 3,
        speed: "normal",
        atqSpeed: 2.50,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [9,6],
    },
    {
        id: 18,
        name: "Princesse",
        hp: 651,
        damages: 173,
        range: 6,
        speed: "normal",
        atqSpeed: 2.00,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [0,2],
    },
    {
        id: 19,
        name: "Electro-sorcier",
        hp: 723,
        damages: 82,
        range: 4,
        speed: "normal",
        atqSpeed: 1.66,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [13,10],
    },
    {
        id: 20,
        name: "Méga-chevalier",
        hp: 1551,
        damages: 103,
        range: 1,
        speed: "Très lent",
        atqSpeed: 1.66,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [12,7],
    },
    {
        id: 21,
        name: "Fantome royal",
        hp: 879,
        damages: 134,
        range: 1,
        speed: "normal",
        atqSpeed: 1.00,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [8,5],
    },
    {
        id: 22,
        name: "Voleuse",
        hp: 869,
        damages: 86,
        range: 1,
        speed: "normal",
        atqSpeed: 1.11,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [12, 5],
    },
    {
        id: 23,
        name: "Machine gobline",
        hp: 1194,
        damages: 86,
        range: 1,
        speed: "normal",
        atqSpeed: 1.20,
        critical: 0.15,
        type: "épique",
        img: ".png",
        cout: 4,
        categories: [8,7],
    },
    // 5 costs --------------------------
    {
        id: 24,
        name: "Roi squelette",
        hp: 1400,
        damages: 180,
        range: 1,
        speed: "Très lent",
        atqSpeed: 2.00,
        critical: 0.15,
        type: "légendaire",
        img: ".png",
        cout: 5,
        categories: [8,1],
    },
    {
        id: 25,
        name: "Chevalier d'or",
        hp: 1200,
        damages: 140,
        range: 1,
        speed: "normal",
        atqSpeed: 1.25,
        critical: 0.15,
        type: "légendaire",
        img: ".png",
        cout: 5,
        categories: [0,5],
    },
    {
        id: 26,
        name: "Reine des archères",
        hp: 849,
        damages: 90,
        range: 4,
        speed: "normal",
        atqSpeed: 1.25,
        critical: 0.15,
        type: "légendaire",
        img: ".png",
        cout: 5,
        categories: [3,11],
    },
];

module.exports = cardsTab;
    
